const OUR_PICKS = [
  {
    id: 1,
    img: './images/main/ourpicks/image-1.jpg',
    link: '',
    text: '블프 위크 최대 65% 증정',
    title: 'Wedidas Korea',
  },
  {
    id: 2,
    img: './images/main/ourpicks/image-2.jpg',
    link: '',
    text: '22 WINTER PART.1',
    title: 'Wecode plus',
  },
  {
    id: 3,
    img: './images/main/ourpicks/image-3.jpg',
    link: '',
    text: '쇼핑가이드 MD추천 겨울 아우터',
    title: 'Sports',
  },
  {
    id: 4,
    img: './images/main/ourpicks/image-4.jpg',
    link: '',
    text: '다이버 크루들의 러블리 아우터 일상',
    title: 'Wecode + Wework',
  },
  {
    id: 5,
    img: './images/main/ourpicks/image-5.jpg',
    link: '',
    text: '아울렛 기간한정 특가+최대 5만원 쿠폰',
    title: 'Wecode',
  },
  {
    id: 6,
    img: './images/main/ourpicks/image-6.jpg',
    link: '',
    text: 'New Arrivals 22 Fall - Winter',
    title: 'WEO WEO ISSEY MIYAKE',
  },
  {
    id: 7,
    img: './images/main/ourpicks/image-7.jpg',
    link: '',
    text: 'Better Together 하나보다 둘이 더 좋은 이벤트',
    title: 'Weanpole Accessory',
  },
  {
    id: 8,
    img: './images/main/ourpicks/image-8.jpg',
    link: '',
    text: 'Your Autumn Cardigun starts here',
    title: 'Weison Kitsune',
  },
  {
    id: 9,
    img: './images/main/ourpicks/image-9.jpg',
    link: '',
    text: '신규입점 특가~70% 사은품 증정',
    title: 'millibam',
  },
  {
    id: 10,
    img: './images/main/ourpicks/image-10.jpg',
    link: '',
    text: "Men's Winter Pants",
    title: 'Weanpole Golf',
  },
  {
    id: 11,
    img: './images/main/ourpicks/image-11.jpg',
    link: '',
    text: '포근한 겨울을 위한 핸드메이드 코트',
    title: 'WEGATIO',
  },
  {
    id: 12,
    img: './images/main/ourpicks/image-12.jpg',
    link: '',
    text: '닥터지, 지아자, 바이탈뷰티 등 뷰티 핫딜 최대 80%',
    title: 'Beauty',
  },
  {
    id: 13,
    img: './images/main/ourpicks/image-13.jpg',
    link: '',
    text: '가장 사랑받는 신상으로 겨울 맞이하기',
    title: 'Rag & Bone',
  },
  {
    id: 14,
    img: './images/main/ourpicks/image-14.jpg',
    link: '',
    text: '소프라움 단독 특가 77%+사은품 증정',
    title: 'SOFRAUM',
  },
  {
    id: 15,
    img: './images/main/ourpicks/image-15.jpg',
    link: '',
    text: '내게 꼭 붙어있어야 할 추위 극복 #핫팩템',
    title: '7 seconds',
  },
  {
    id: 16,
    img: './images/main/ourpicks/image-16.jpg',
    link: '',
    text: 'ALITA, NEW ARRIVALS',
    title: '10 CORSO COME',
  },
  {
    id: 17,
    img: './images/main/ourpicks/image-17.jpg',
    link: '',
    text: '경량 패딩&조끼 더 가볍게, 따뜻하게',
    title: '7 seconds',
  },
  {
    id: 18,
    img: './images/main/ourpicks/image-18.jpg',
    link: '',
    text: '22AW OPENING UP TO55%+10% OFF',
    title: 'TATRAS',
  },
  {
    id: 19,
    img: './images/main/ourpicks/image-19.jpg',
    link: '',
    text: '블랙프라이데이 단독~50%',
    title: 'MARITHE FRANCOIS GIRBAUD',
  },
  {
    id: 20,
    img: './images/main/ourpicks/image-20.jpg',
    link: '',
    text: '베스트 리뷰 남기고, 사은품 받기!',
    title: 'Theory',
  },
];

export default OUR_PICKS;
